[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "simulation"
dynamic = ["version"]
dependencies = [
    "python-dotenv",
    "typing_extensions"
]

[project.scripts]
simulation = "main:main"

[tool.setuptools.packages.find]
where = ["."]
